More resource additions
TheCodex6824/ThaumcraftFix pull request #19
Opened 2024-07-11 08:17 UTC by IcarussOne

- Added a recipe to craft 9 sliver back into quartz, it made no sense that there was no recipe for this so here it is.
- Added subtitles (as mentioned in #6), had to really think on what would fit best for these especially because they are used for several features in the mod itself and in addons. Feel free to review and rename any subtitles that don't seem to fit!
- Added back the page turn sounds from older Thaumcraft versions as extra page turning sounds.

For subtitles that are from reused Minecraft sounds, that can't really be fixed unless you make new sound entries that reuse those vanilla sounds with new subtitles. Unfortunately this is an issue in several mods.

2024-07-11 11:12 UTC, Vapaman commented
I think the sliver to quartz recipe wasn't included to be more consistent with how vanilla lacks the quartz block to quartz recipe

2024-07-11 17:09 UTC, TechnoMysterio commented
Looks good at a glance, a few suggestions for the subtitles:
- "Brain whispers" -> "Eerie breathing", I think it might be used in a few other places than the Brain in a Jar
- "Eldritch Crab communicates" -> "Eldritch Crab gibbers" or "chitters"
- "Crystal shines" -> "Crystal clinks", since it's used for footsteps too
- "Magical noise" -> "Magical shimmer", for added flair
- "Eldritch Guardian chants angrily" -> "Eldritch Guardian moans"
- "Disturbing portal noise" -> "Unearthly howling", to be a bit more generic
- "Taint explodes" -> "Squelch", since gore1-2.ogg are used for footsteps too
- "Jar noise" -> "Jar clanks"
- "Page crumbles" -> "Paper shuffles"
- "Pumping noise" -> "Contraption rattles"
- "Runic Shield charges/protects" -> "Magical shield charges/hums", since it's used for magic shields in general
- "Mechanism breaks" -> "Contraption clanks", it's used for connecting essentia tubes so "break" doesn't make sense
- "Infusion finishes" -> "Magical sparkle", it's used for a few devices when crafting is complete, Focal Manipulator, Golem Press, etc
- "Portal summons" -> "Magical warble", again it's used for a few things outside of just crimson portals, like failed crafting
- "Windy noise" -> "Wind whistles"
- "Wisp communicates" -> "Wisp sparkles"

2024-07-12 01:25 UTC, TheCodex6824 requested changes
Looks pretty good, just needs some minor changes on the recipe.

2024-07-12 01:25 UTC, TheCodex6824 commented on src/main/resources/assets/thaumcraftfix/recipes/quartz_sliver_to_block.json
> +{
This file is named as if it gives quartz blocks, but it gives the item, so it is a bit confusing

2024-07-12 01:25 UTC, TheCodex6824 commented on src/main/resources/assets/thaumcraftfix/recipes/quartz_sliver_to_block.json
> +      "item": "thaumcraft:nugget",
Thaumcraft registers quartz slivers as `nuggetQuartz` in the ore dictionary, so using that here would be better than hardcoding the item

2024-07-12 01:27 UTC, TheCodex6824 commented
> I think the sliver to quartz recipe wasn't included to be more consistent with how vanilla lacks the quartz block to quartz recipe

I don't mind adding this quartz recipe since it's just a QOL conversion from slivers to the item, and you would have needed to have the item to get the slivers anyway. Going from the block to item is a bigger deal because then people could take apart structures to get quartz (I remember using the IE crusher to do that a lot).

2024-07-13 23:09 UTC, TheCodex6824 commented
The recipe is good now, thanks. I tried to figure out where the page sounds came from, and while we couldn't find the exact sounds (already not great), the sounds from tc6 were taken from a place with a license incompatible with the LGPL license of this mod. Unfortunately, because of that I think it would be best to remove those sounds for now.

You'll have to do an interactive rebase of this PR to get rid of the commit adding the sounds due to how Git works - just making a new commit deleting the sounds is not enough to remove them fully from the repo. If you don't know how to do that I can do it for you, although I'm probably going to have to push them to your branch first so the PR doesn't get confused and marked as closed like last time.

2024-07-13 23:37 UTC, closed without merging

2024-07-13 23:42 UTC, TheCodex6824 commented
Github once again did not appreciate my attempt to be clever, but this was merged.

2024-07-13 23:50 UTC, TheCodex6824 commented
> Awesome! Really appreciate the help!

No problem, thanks for your contributions :)